# LDA Handson
    as LDA is supervised while transforming the data we need to consider Target variable

    📌 Steps for LDA Implementation
    1️⃣ Standardize the Data – Ensure all features have the same scale.
    2️⃣ Compute the Mean Vectors – Find the mean for each class.
    3️⃣ Compute the Within-Class Scatter Matrix (Sw) – Measures spread within each class.
    4️⃣ Compute the Between-Class Scatter Matrix (Sb) – Measures spread between classes.
    5️⃣ Compute Eigenvalues & Eigenvectors – Find the best projection direction.
    6️⃣ Select Top k Eigenvectors – Choose the components that capture the most class separability.
    7️⃣ Project Data onto New Axes – Transform the original data into the new space.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [4]:
#for the inbuild dataset
from sklearn.datasets import load_digits 
dataset=load_digits() 

In [6]:
dataset

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [8]:
dataset["data"]

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [10]:
df=pd.DataFrame(dataset["data"]) 
df 

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [12]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
59    0
60    0
61    0
62    0
63    0
Length: 64, dtype: int64

In [14]:
df.duplicated().sum()

0

In [16]:
#splitting the data into indepedent and dependent
X=df
y=dataset["target"]

In [18]:
X

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [20]:
y 

array([0, 1, 2, ..., 8, 9, 8])

In [26]:
#preprocessig of date : standardinze the data

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Scaled_X=sc.fit_transform(X)

In [28]:
Scaled_X

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [32]:
Scaled_X=pd.DataFrame(Scaled_X,columns=X.columns)

In [34]:
Scaled_X

0         1         2         3         4         5         6   \
0     0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724   
1     0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724   
2     0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724   
3     0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724   
4     0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724   
...   ...       ...       ...       ...       ...       ...       ...   
1792  0.0 -0.335016 -0.253452 -0.432200  0.268751  0.038508 -0.409724   
1793  0.0 -0.335016  0.167290  0.980343  0.268751  0.921145 -0.108958   
1794  0.0 -0.335016 -0.884566 -0.196776  0.735366 -0.844129 -0.409724   
1795  0.0 -0.335016 -0.674195 -0.432200 -1.131092 -1.020657 -0.409724   
1796  0.0 -0.335016  1.008775  0.509495 -0.897785 -0.844129 -0.409724   

            7         8         9   ...        54        55        56  \
0    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
1    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
2    -0.125023 -0.059078 -0.624009  ...  0.259230 -0.209785 -0.023596   
3    -0.125023 -0.059078  1.879691  ...  1.072563 -0.209785 -0.023596   
4    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
...        ...       ...       ...  ...       ...       ...       ...   
1792 -0.125023 -0.059078 -0.311047  ...  0.055897 -0.209785 -0.023596   
1793 -0.125023 -0.059078 -0.624009  ... -0.554103 -0.209785 -0.023596   
1794 -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
1795 -0.125023 -0.059078 -0.624009  ... -0.350769 -0.209785 -0.023596   
1796 -0.125023 -0.059078  0.001916  ...  0.869229 -0.209785 -0.023596   

            57        58        59        60        61        62        63  
0    -0.299081  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1    -0.299081 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2    -0.299081 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3    -0.299081  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4    -0.299081 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  
...        ...       ...       ...       ...       ...       ...       ...  
1792 -0.299081 -0.697349  0.436944  0.646898  0.379040 -0.505670 -0.196008  
1793 -0.299081  0.086719  0.894246  0.444164 -0.129523 -0.505670 -0.196008  
1794 -0.299081 -0.697349 -0.706312  0.241430 -0.129523 -0.505670 -0.196008  
1795 -0.299081 -0.109298 -0.020358  0.849632  0.887602 -0.505670 -0.196008  
1796  0.771535  0.478753 -0.020358  0.444164  0.887602 -0.261136 -0.196008  

[1797 rows x 64 columns]

In [36]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [40]:
lda_model=LinearDiscriminantAnalysis(n_components=9)

In [48]:
lda_model.fit_transform(Scaled_X,y)
#passsing the target also along with independent data as lda uses these targets for seperability

array([[ 2.01463220e+00,  5.62348616e+00, -1.86594028e-01, ...,
        -1.09348511e-01, -1.83506669e-01, -9.65495420e-01],
       [-2.20967396e-01, -3.59240033e+00,  2.14901657e+00, ...,
        -1.23115093e-01, -3.39210556e+00,  1.20766919e+00],
       [-2.23485453e+00, -2.70950363e+00,  4.26992781e+00, ...,
         2.51256615e+00,  1.08370006e+00, -4.22490736e-03],
       ...,
       [ 1.04697178e+00, -1.48367733e+00,  3.04170263e+00, ...,
         1.54913444e+00,  1.99315402e+00, -2.17737830e+00],
       [-4.07872916e-01,  1.99167301e+00, -3.65835518e-01, ...,
         9.16595358e-01,  5.26856349e-01,  1.41509141e+00],
       [-1.74145011e-01, -8.87174627e-01,  1.37776831e+00, ...,
        -5.14965352e-02,  3.18833067e+00, -6.91242304e-01]])

In [50]:
lda_X=pd.DataFrame(lda_X)

In [52]:
lda_X #new indepennt column

0         1         2         3         4         5         6  \
0     2.014632  5.623486 -0.186594 -2.800109  0.443373  0.579755 -0.109349   
1    -0.220967 -3.592400  2.149017 -0.114046 -2.054971 -2.222544 -0.123115   
2    -2.234855 -2.709504  4.269928 -2.147419  1.737674 -1.281434  2.512566   
3    -2.760965  0.624427  0.158751  1.247578 -0.066359  0.805282 -2.963266   
4     5.845449 -1.754015  0.400295 -1.376300 -0.312251 -0.461142 -1.367118   
...        ...       ...       ...       ...       ...       ...       ...   
1792 -1.213858  2.473313 -1.984814 -1.718768 -2.833563  0.014869  0.445814   
1793  2.456013  4.420402  0.637759 -1.306113  1.985565 -0.233411  0.648579   
1794  1.046972 -1.483677  3.041703 -0.604862 -2.812749  2.039136  1.549134   
1795 -0.407873  1.991673 -0.365836 -2.168076 -2.263624  0.142661  0.916595   
1796 -0.174145 -0.887175  1.377768  0.339951 -2.235620  1.839580 -0.051497   

             7         8  
0    -0.183507 -0.965495  
1    -3.392106  1.207669  
2     1.083700 -0.004225  
3    -1.575261 -0.020835  
4     0.665557 -0.132020  
...        ...       ...  
1792  2.020741  0.947234  
1793 -1.462323 -0.443657  
1794  1.993154 -2.177378  
1795  0.526856  1.415091  
1796  3.188331 -0.691242  

[1797 rows x 9 columns]

In [54]:
y #dependent

array([0, 1, 2, ..., 8, 9, 8])

# model building 


In [57]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test, y_train, y_test = train_test_split(lda_X, y, test_size=0.3,random_state=42)

In [61]:
dt_model = DecisionTreeClassifier()

In [63]:
#training of model
dt_model.fit(x_train, y_train) 

DecisionTreeClassifier()

In [65]:
# testing the model
y_pred = dt_model.predict(x_test) 

In [67]:
y_pred

array([6, 9, 3, 7, 2, 2, 5, 2, 5, 2, 1, 9, 4, 0, 4, 2, 3, 7, 8, 6, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 3, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 8, 0, 9, 0, 0, 1, 2, 4, 5, 2, 6, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 2, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 4, 4, 4, 4, 3, 5, 3, 1, 3, 5, 8, 4, 2,
       7, 7, 4, 6, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 9, 0, 6, 6, 4, 2, 9, 0, 9, 4, 6, 9, 9, 6, 9, 0, 5, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 4, 7, 2, 3, 0, 4, 5, 3, 6, 5, 9, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 8, 2, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 1, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 8, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 9, 1, 4, 7, 6, 5, 1, 5,
       5, 3, 4, 8, 8, 8, 9, 8, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 3, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [69]:
y_test

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 0, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 7, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 3, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 9, 7, 2, 9, 0, 4, 5, 3, 6, 5, 9, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 5, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 8, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 5, 1, 4, 7, 6, 8, 8, 5,
       5, 1, 6, 2, 8, 8, 9, 9, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 9, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [71]:
from sklearn.metrics import *

In [73]:
accuracy_score(y_test,y_pred)

0.8962962962962963

### random forest

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
rf_model=RandomForestClassifier()  

In [84]:
#training the model
rf_model.fit(x_train,y_train)

RandomForestClassifier()

In [92]:
#testing of model
y_pred=rf_model.predict(x_test)

In [94]:
y_pred

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 3, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 4, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 9, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 5, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 8, 7, 2, 9, 0, 4, 5, 3, 6, 5, 8, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 5, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 1, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 9, 1, 4, 7, 6, 9, 1, 5,
       5, 1, 4, 2, 8, 8, 9, 8, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 3, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [96]:
y_test

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 0, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 7, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 3, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 9, 7, 2, 9, 0, 4, 5, 3, 6, 5, 9, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 5, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 8, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 5, 1, 4, 7, 6, 8, 8, 5,
       5, 1, 6, 2, 8, 8, 9, 9, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 9, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [98]:
accuracy_score(y_test,y_pred)

0.9611111111111111

LDA predict better result that PCA  
LDA is classification algorith only take sepeation into consideration  

* LDA focus on better seperability  
* PCA focus on better variance  